### ISSUE TITLE
Slick.css sets overreaching styles on paragraphs and lists

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/ItemCarouselBlock#14]
```
p, ul {
        margin: 0;
}
```

My page content ends up having many fewer margins when this block is present.

**Comment by kimisgold** [comment]
It looks like there were actually a bunch of changes made to the original `slick.css`, and they should probably go into `asset/css/item-carousel.css`. @matthewjmckinley, can you move any changes specific to the module over?

**Comment by matthewjmckinley** [comment]
Whoops! Specific changes moved to item-carousel.css and slick.css reverted to stock here: https://github.com/omeka-s-modules/ItemCarouselBlock/commit/5019eff669f259a44f74d6397b818e42bcbb5212
