### ISSUE TITLE
Test carousel w/ new accessible-slick library

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/ItemCarouselBlock#16]
In response to some raised accessibility issues (see... other issues), I've replaced the standard `slickjs` base code library with `accessible-slick`. This required some reworking of our customizations/options for the carousel, so please test that the following still work:

- adding/removing/re-ordering items with thumbnails of different size and shape
- adding titles and captions of various lengths
- with a test set of various size images/captions, adjusting each of the settings on their own and together
- remaining settings

I've also made some changes in response to Issue #15, to ensure that multiple carousels on a page retain their own unique settings, so also please test different settings with 2 or more carousels on the page to ensure they all work as expected. Thank you!

**Comment by allanaaa** [comment]
Everything on one carousel seems to work fine. When the "overlay title and caption" option is checked, the dot-links that are supposed to sit underneath the images are now partially hidden under the images.
![overlay](https://github.com/omeka-s-modules/ItemCarouselBlock/assets/28012148/16b3b584-3d4b-4750-a4b8-174c89b7c602)

When I added a second carousel, they are definitely picking up each other's settings. They do _appear_ to retain their original settings in the admin side, but don't work that way on public.

**Comment by matthewjmckinley** [comment]
Hmmm I'm not able to replicate the hidden dot issue. Can you share your settings and, if possible, the media that you're seeing the issue happen with?

Same with the double carousels, the settings are remaining distinct per carousel for me. Are you certain you've pulled the latest code? I put in the fix for this just last night.

Alternately, if you're testing on the dev server let me know which and I can poke around there.

**Comment by katknow** [comment]
It seems to be working or me. I've mixed up the settings and so far have tried it with default, center row, cozy, the daily, and foundation.

**Comment by allanaaa** [comment]
Yep, working now! I must not have installed it from git initially. Ignore all my above comments.
