### ISSUE TITLE
Items should show correct-language values according to site locale

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/ItemCarouselBlock#17]
Items in the carousel should show a specific language-tagged title when a site setting enforces a locale. Currently it ignores a locale preference and only shows the first title value.

**Comment by matthewjmckinley** [comment]
Fixed in https://github.com/omeka-s-modules/ItemCarouselBlock/commit/bfaf833d6b1bf000d8a821847625a14e4f1f6e47
