### ISSUE TITLE
Adding a link in the caption of an image places the caption in a slide

### ISSUE THREAD

**Issue by coolidfrez** [omeka-s-modules/ItemCarouselBlock#18]
Hi !

Normally, the caption is displayed below the slide, but as soon as we add a link inside, it is displayed within the slider.

Here's some pictures to illustrate the problem :

![Sans titre](https://github.com/omeka-s-modules/ItemCarouselBlock/assets/1484445/0b38591f-2ef9-4532-ae2e-369b53a146cd)

![image](https://github.com/omeka-s-modules/ItemCarouselBlock/assets/1484445/e1853cc0-0ec4-47fd-8335-f7c035ba02b5)

All my thanks and once again, congratulations for this module!

PS : my version is 1.2.1

**Comment by matthewjmckinley** [comment]
Hello! Thanks for catching this. We are creating each slide's content as a direct link to the item, and I think adding another embedded link to the title/caption was confusing the Slick.JS library and causing it treat the link as a distinct slide. Wrapping each slide's content in a <div> seems to sort things out.

Bug should be fixed if you pull the latest code, and we'll have a new bugfix version out soon!
