### ISSUE TITLE
Carousel page block arrows sit outside dimensions

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/ItemCarouselBlock#20]
<img width="948" alt="Screenshot 2024-02-22 at 15 32 37" src="https://github.com/omeka-s-modules/ItemCarouselBlock/assets/28012148/5d40c1da-90e1-46d2-b354-9c3cd806ce6f">

For the most part users will put a carousel block at the full page width, but if it's floated in normal flow, or getting a limited width in grid flow, the arrows will sit outside its required dimensions and possibly overflow into another container. 

(It's the only thing I've seen so far in the new grid layout that is overflowing its width like this, so I would release this with S 4.1.)

**Comment by kimisgold** [comment]
This happens in normal flow context as well but might not be as noticeable. I've pushed a fix that keeps the arrows within the width of the content container.
