### ISSUE TITLE
Safari - Slide images do not maintain original ratio

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/ItemCarouselBlock#3]
This is using large fullsize images.

![Screen Shot 2021-03-19 at 11 40 13 AM](https://user-images.githubusercontent.com/606764/111806078-fec26200-88a7-11eb-918a-ce8c3b73cbca.png)

**Comment by matthewjmckinley** [comment]
I _think_ I fixed this on a recent commit with `align-items: center` https://github.com/omeka-s-modules/ItemCarouselBlock/commit/6db7946779497f62812d34f6d07cd90aad65c419

**Comment by kimisgold** [comment]
Looks good!
