### ISSUE TITLE
Improve output of "stretch to fill slide"

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/ItemCarouselBlock#4]
Right now it seems that the output of the "stretch to fill slide" option sets both width and height to 100%, which would require that all the items share the same aspect ratio to avoid stretching. To provide more flexibility, I would recommend this setting be a select input with the following options: 

* stretch to fill width
* stretch to fill height
* cover whole carousel area (this would fill the width and height but maybe use `background-size:cover`, which would maintain the media's aspect ratio and crop what doesn't fit in the space)

**Comment by matthewjmckinley** [comment]
Fixed in da937c9e
