### ISSUE TITLE
When multiple slides show simultaneously, images can extend beyond their container

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/ItemCarouselBlock#6]
![image](https://user-images.githubusercontent.com/606764/112871369-3346d280-908d-11eb-9aa4-9495d870b781.png)

**Comment by matthewjmckinley** [comment]
I'm not able to recreate this... could you share your settings, and maybe the dimensions of the image that's breaking the container?

**Comment by kimisgold** [comment]
I suspect it has to do with that first image. It's 1996x840.

![image](https://user-images.githubusercontent.com/606764/113189108-d41dc500-9228-11eb-9702-10e4b290ccd9.png)

**Comment by sharonmleon** [comment]
@kimisgold Any thoughts on a fix here? 
(This is final outstanding issue on this module.)

**Comment by matthewjmckinley** [comment]
I don't think I ever was able to reproduce this one. I'm testing now with multiple images larger than 1996x840, and it's resizing them fine with 2, 3, 4, etc. items for page. I may have tweaked the CSS to handle this better at some point? @kimisgold is this still happening for you or can we consider this fixed?

**Comment by kimisgold** [comment]
This is happening in the following themes:
* Center Row
* The Daily
* Cozy

The themes where this isn't happening have `max-width: 100%` set on all images by default.

**Comment by matthewjmckinley** [comment]
Fixed by https://github.com/omeka-s-modules/ItemCarouselBlock/commit/577b947ca16a639c79a372e5a035e6d09e07a72f
